version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: handraiserdb
    ports:
      - 5432:5432
    volumes:
      - handraiserdb:/var/lib/postgresql/data
volumes:
  handraiserdb:
